my_notifications/urls.py
from django.urls import path
from . import views

app_name = "my_notifications"

urlpatterns = [
	path('', views.my_notifications, name="my_notifications"),
    path('my_notification<int:my_notification_pk>/', views.my_notification, name="my_notification"),
    path('delete_my_read_notifications/', views.delete_my_read_notifications, name="delete_my_read_notifications"),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('login_for_modal/', views.login_for_modal, name="login_for_modal"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('user_info/', views.user_info, name="user_info"),
    path('change_nickname/', views.change_nickname, name="change_nickname"),
    path('bind_email/', views.bind_email, name="bind_email"),
    path('send_verfication_code/', views.send_verfication_code, name="send_verfication_code"),
    path('change_password/', views.change_password, name="change_password"),
    path('forgot_password', views.forgot_password, name="forgot_password"),
]

my_notifications/models.py
from django.db import models

# Create your models here.

my_notifications/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from notifications.models import Notification

# 查看站内消息
def my_notifications(request):
	return render(request, 'my_notifications/my_notifications.html')

# 查看具体某一条消息，并把它标记为已读
def my_notification(request, my_notification_pk):
	my_notification = get_object_or_404(Notification, pk=my_notification_pk)
	my_notification.unread = False
	my_notification.save()
	return redirect(my_notification.data['url'])

# 删除全部已读消息
def delete_my_read_notifications(request):
	notifications = request.user.notifications.read()
	notifications.delete()
	return redirect(reverse('my_notifications:my_notifications'))

my_notifications/templates/my_notifications/my_notifications.html
{% extends 'user/user_info.html' %}
{% load staticfiles %}
{% block message_status %}active{% endblock %}

{% block title %}小黑阅读站|我的消息{% endblock %}

{% block header %}
	<link rel="stylesheet" type="text/css" href="{% static 'my_notifications/notifications.css' %}">
{% endblock header%}

{% block info_content %}
	<div class="base-info">
		<div class="row">
			<div class="col-xs-6 col-xs-offset-3 message">
				<ul class="notifications">
					{% for notification in request.user.notifications.all %}
						<li class="{% if not notification.unread %}read{% endif %}">
							[{{ notification.timesince }}之前]
							<a href="{% url 'my_notifications:my_notification' notification.pk %}">
								{{ notification.verb }}
							</a>
						</li>
					{% empty %}
						<li>暂无消息</li>
					{% endfor %}
				</ul>
				<a class="btn btn-primary" href="{% url 'notifications:mark_all_as_read' %}?next={% url 'my_notifications:my_notifications' %}">
					全部标记为已读
				</a>
				<a class="btn btn-danger" href="{% url 'my_notifications:delete_my_read_notifications' %}">删除已读消息</a>
			</div>
		</div>
	</div>
{% endblock %}