collect/urls.py
from django.urls import path
from . import views

app_name = "collect"

urlpatterns = [
	path('collect_change/', views.collect_change, name="collect_change"),
	path('my_collects/', views.my_collects, name="my_collects"),
	path('delete_collect<int:collect_pk>', views.delete_collect, name="delete_collect"),
]

novels/urls.py
from django.urls import path
from . import views

app_name = 'novels'

urlpatterns = [
    path('type<int:type_pk>/', views.type, name="type"),
    path('novel_detail<int:novel_pk>', views.novel_detail, name="novel_detail"),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('login_for_modal/', views.login_for_modal, name="login_for_modal"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('user_info/', views.user_info, name="user_info"),
    path('change_nickname/', views.change_nickname, name="change_nickname"),
    path('bind_email/', views.bind_email, name="bind_email"),
    path('send_verfication_code/', views.send_verfication_code, name="send_verfication_code"),
    path('change_password/', views.change_password, name="change_password"),
    path('forgot_password', views.forgot_password, name="forgot_password"),
]

collect/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User

class CollectRecord(models.Model):
	content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
	object_id = models.PositiveIntegerField()
	content_object = GenericForeignKey('content_type', 'object_id')

	user = models.ForeignKey(User, on_delete=models.CASCADE)
	collected_time = models.DateTimeField(auto_now_add=True)

collect/views.py
from django.shortcuts import render, redirect
from django.contrib.contenttypes.models import ContentType
from django.http import JsonResponse
from django.db.models import ObjectDoesNotExist
from .models import CollectRecord


# 返回正确操作的JSON数据
def SuccessResponse():
    data = {}
    data['status'] = 'SUCCESS'
    return JsonResponse(data)


# 返回错误操作的JSON数据
def ErrorResponse(code, message):
    data = {}
    data['status'] = 'ERROR'
    data['code'] = code
    data['message'] = message
    return JsonResponse(data)


# 收藏操作逻辑函数
def collect_change(request):
    # 获取数据
    user = request.user
    # 如果用户没有登录
    if not user.is_authenticated:
        return ErrorResponse(400, '您还没有登录')

    content_type = request.GET.get('content_type')
    object_id = request.GET.get('object_id')

    try:
        # 获取要收藏的对象
        content_type = ContentType.objects.get(model=content_type)
        model_class = content_type.model_class()
        model_obj = model_class.objects.get(pk=object_id)
    except ObjectDoesNotExist:
        return ErrorResponse(401, '点赞对象不存在')

    # 判断是否已经收藏过
    is_collect = request.GET.get('is_collect')

    # 如果还没有收藏过
    if is_collect == 'true':
        # 要进行收藏，检查是否有收藏记录
        collect_record, created = CollectRecord.objects.get_or_create(content_type=content_type,
                                                                      object_id=object_id,
                                                                      user=user)
        if created:
            # 刚创建好收藏记录
            return SuccessResponse()
        else:
            # 已经收藏过，不能重复收藏
            return ErrorResponse(402, '不能重复收藏')
        # 取消收藏
    else:
        # 如果存在收藏记录，则删除这条记录
        if CollectRecord.objects.filter(content_type=content_type, object_id=object_id, user=user).exists():
            collect_record = CollectRecord.objects.get(content_type=content_type, object_id=object_id, user=user)
            collect_record.delete()
            return SuccessResponse()
        # 如果不存在收藏记录，则返回错误
        else:
            return ErrorResponse(403, '还没有收藏过，不能取消')



def my_collects(request):
    context = {}
    user = request.user
    collect_records = CollectRecord.objects.filter(user=user).order_by("-collected_time")
    context['collect_records'] = collect_records
    return render(request, 'collect/my_collects.html', context)

def delete_collect(request, collect_pk):
    if CollectRecord.objects.filter(pk=collect_pk).exists():
        collect_record = CollectRecord.objects.get(pk=collect_pk)
        collect_record.delete()
        return redirect('collect:my_collects')

collect/templates/collect/my_collects.html
{% extends 'user/user_info.html' %}
{% load staticfiles %}
{% block collect_status %}active{% endblock %}

{% block title %}小黑阅读站|我的消息{% endblock %}

{% block header %}
	<link rel="stylesheet" type="text/css" href="{% static 'collect/my_collects.css' %}">
{% endblock header%}

{% block info_content %}
	<div class="base-info">
		<div class="row">
			<div class="col-xs-8 col-xs-offset-2 collect">
				<ul class="collect_records">
					<li class="li-header">
						<span>书名</span>
						<span>收藏时间</span>
						<span>操作</span>
					</li>
					{% for collect_record in collect_records %}
						<li>
							<span>
								<a href="{% url 'novels:novel_detail' collect_record.content_object.pk %}">
									{{ collect_record.content_object.get_name }}
								</a>
							</span>
							<span>{{ collect_record.collected_time }}</span>
							<span class="delete">
								<a class="btn btn-danger" href="{% url 'collect:delete_collect' collect_record.pk %}">取消收藏</a>
							</span>
						</li>
					{% empty %}
						<li>暂无收藏</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
{% endblock %}