collect/urls.py
from django.urls import path
from . import views

app_name = "collect"

urlpatterns = [
	path('collect_change/', views.collect_change, name="collect_change"),
	path('my_collects/', views.my_collects, name="my_collects"),
	path('delete_collect<int:collect_pk>', views.delete_collect, name="delete_collect"),
]

my_notifications/urls.py
from django.urls import path
from . import views

app_name = "my_notifications"

urlpatterns = [
	path('', views.my_notifications, name="my_notifications"),
    path('my_notification<int:my_notification_pk>/', views.my_notification, name="my_notification"),
    path('delete_my_read_notifications/', views.delete_my_read_notifications, name="delete_my_read_notifications"),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('login_for_modal/', views.login_for_modal, name="login_for_modal"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('user_info/', views.user_info, name="user_info"),
    path('change_nickname/', views.change_nickname, name="change_nickname"),
    path('bind_email/', views.bind_email, name="bind_email"),
    path('send_verfication_code/', views.send_verfication_code, name="send_verfication_code"),
    path('change_password/', views.change_password, name="change_password"),
    path('forgot_password', views.forgot_password, name="forgot_password"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	nickname = models.CharField(max_length=20)

	def __str__(self):
		return '<Profile: %s for %s>' % (self.nickname,self.user.username)

def get_nickname(self):
	if Profile.objects.filter(user=self).exists():
		profile = Profile.objects.get(user=self)
		return profile.nickname
	else:
		return ''

def get_nickname_or_username(self):
	if Profile.objects.filter(user=self).exists():
		profile = Profile.objects.get(user=self)
		return profile.nickname
	else:
		return self.username

def has_nickname(self):
	return Profile.objects.filter(user=self).exists()

User.get_nickname = get_nickname
User.has_nickname = has_nickname
User.get_nickname_or_username = get_nickname_or_username

user/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User

# 自定义用户登录表单
class LoginForm(forms.Form):
	username = forms.CharField(label='用户名', widget=forms.TextInput(attrs={'class':'form-control',
																'placeholder':'请输入用户名'}))
	password = forms.CharField(label='密码', widget=forms.PasswordInput(attrs={'class':'form-control',
																'placeholder':'请输入密码'}))

	def clean(self):
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']
		user = auth.authenticate(username=username, password=password)
		if user is None:
			raise forms.ValidationError('用户名或密码错误！')
		else:
			self.cleaned_data['user'] = user
		return self.cleaned_data


# 自定义用户注册表单
class RegisterForm(forms.Form):
    username = forms.CharField(
    	label='用户名',
        max_length=30,
        min_length=3,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请输入3-30位用户名'})
    )

    nickname = forms.CharField(
    	label='昵称',
    	max_length=20,
    	required=False,
    	widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '请输入昵称'})
    )
    email = forms.EmailField(
    	label='邮箱',
    	required=False,
     	widget=forms.EmailInput(
        	attrs={'class': 'form-control', 'placeholder': '请输入邮箱'})
    )

    verification_code = forms.CharField(
        label='验证码',
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '点击"发送验证码"发送到邮箱'}
        )
    )

    password = forms.CharField(
    	label='密码',
    	min_length=6,
        max_length=20,
        widget=forms.PasswordInput(
           	attrs={'class': 'form-control', 'placeholder': '请输入密码'})
    )

    password_again = forms.CharField(
    	label='确认密码',
    	min_length=6,
     	max_length=20,
     	widget=forms.PasswordInput(
         	attrs={'class': 'form-control', 'placeholder': '请再次输入密码'})
    )

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('用户名已存在')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱已存在')
        return email

    def clean_password_again(self):
        password = self.cleaned_data['password']
        password_again = self.cleaned_data['password_again']
        if password_again != password:
            raise forms.ValidationError('两次密码不一致')
        return password

    def clean_verification_code(self):
        # 判断验证码是否为空
        verification_code = self.cleaned_data.get('verification_code', '').strip()
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')
        
        # 判断验证码是否正确
        code = self.request.session.get('forgot_password_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')

        return verification_code


# 自定义修改昵称表单
class ChangeNicknameForm(forms.Form):
	nickname_new = forms.CharField(
		label='昵称', 
		max_length=20,
		widget=forms.TextInput(
			attrs={'class':'form-control', 'placeholder':'请输入新的昵称'}
		)
	)

	def __init__(self, *args, **kwargs):
		if 'user' in kwargs:
			self.user = kwargs.pop('user')
		super(ChangeNicknameForm, self).__init__(*args, **kwargs)

	def clean(self):
		# 判断用户是否登录
		if self.user.is_authenticated:
			self.cleaned_data['user'] = self.user
		else:
			raise forms.ValidationError('用户未登录')
		return self.cleaned_data

	def clean_nickname_new(self):
		nickname_new = self.cleaned_data.get('nickname_new', '').strip()
		if nickname_new == '':
			raise forms.ValidationError("昵称不能为空")
		return nickname_new



# 自定义绑定邮箱表单
class BindEmailForm(forms.Form):
	email = forms.EmailField(
		label='邮箱', 
		widget=forms.TextInput(
			attrs={'class':'form-control', 'placeholder':'请输入正确的邮箱'}
		)
	)
	verification_code = forms.CharField(
		label='验证码', 
		required=False,
		widget=forms.TextInput(
			attrs={'class':'form-control', 'placeholder':'点击"发送验证码"发送到邮箱'}
		)
	)

	def clean_email(self):
		email = self.cleaned_data['email']
		if User.objects.filter(email=email).exists():
			raise forms.ValidationError('该邮箱已经被绑定')
		return email

	def clean_verification_code(self):
		verification_code = self.cleaned_data.get('verification_code', '').strip()
		if verification_code == '':
			raise forms.ValidationError('验证码不能为空')
		return verification_code

	def __init__(self, *args, **kwargs):
		if 'request' in kwargs:
			self.request = kwargs.pop('request')
		super(BindEmailForm, self).__init__(*args, **kwargs)

	def clean(self):
		# 判断用户是否登录
		if self.request.user.is_authenticated:
			self.cleaned_data['user'] = self.request.user
		else:
			raise forms.ValidationError('用户未登录')

		# 判断用户是否已经绑定邮箱
		if self.request.user.email != '':
			raise forms.ValidationError('您已经绑定过邮箱')

		# 判断验证码
		code = self.request.session.get('bind_email_code', '')
		verification_code = self.cleaned_data.get('verification_code', '')
		if not (code != '' and code == verification_code):
			raise forms.ValidationError('验证码不正确')

		return self.cleaned_dat

# 自定义修改密码表单
class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(
        label='旧密码', 
        widget=forms.PasswordInput(
            attrs={'class': 'form-control','placeholder': '请输入旧密码'}
        )
    )

    new_password = forms.CharField(
        label='新密码', 
        max_length=20,
        min_length=6,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control','placeholder': '请输入新密码'}
        )
    )

    new_password_again = forms.CharField(
        label='确认密码', 
        max_length=20,
        min_length=6,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control','placeholder': '请再次输入密码'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 验证新密码是否一致
        new_password = self.cleaned_data.get('new_password', '')
        new_password_again = self.cleaned_data.get('new_password_again', '')
        if new_password != new_password_again or new_password == '':
            raise forms.ValidationError('两次输入的密码不一致')
        return self.cleaned_data

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password', '')
        # 验证旧密码是否正确
        if not self.user.check_password(old_password):
            raise forms.ValidationError('旧密码不正确')
        return old_password

# 自定义找回密码表单
class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(
        label='邮箱',
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': '请输入绑定的邮箱'}
        )
    )

    verification_code = forms.CharField(
        label='验证码',
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '点击"发送验证码"发送到邮箱'}
        )
    )

    new_password = forms.CharField(
        label='新密码', 
        max_length=20,
        min_length=6,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control','placeholder': '请输入新密码'}
        )
    )

    new_password_again = forms.CharField(
        label='确认密码', 
        max_length=20,
        min_length=6,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control','placeholder': '请再次输入密码'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(ForgotPasswordForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get('email', '').strip()
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱不存在')
        return email

    def clean_verification_code(self):
        # 判断验证码是否为空
        verification_code = self.cleaned_data.get('verification_code', '').strip()
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')
        
        # 判断验证码是否正确
        code = self.request.session.get('forgot_password_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')

        return verification_code

user/views.py
import string
import random
import time

from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.core.mail import send_mail

from .forms import LoginForm, RegisterForm, ChangeNicknameForm, BindEmailForm, ChangePasswordForm, ForgotPasswordForm
from .models import Profile

# 进入登录页面
def login(request):
	redirect_to = request.GET.get('from', '/')
	if request.method == "POST":
		login_form = LoginForm(request.POST)
		if login_form.is_valid():
			user = login_form.cleaned_data['user']
			auth.login(request, user)
			return redirect(redirect_to)
	else:
		login_form = LoginForm()
	context = {}
	context['login_form'] = login_form
	return render(request, 'user/login.html', context)

# 浮窗登录
def login_for_modal(request):
	data = {}
	login_form = LoginForm(request.POST)
	if login_form.is_valid():
		user = login_form.cleaned_data['user']
		auth.login(request, user)
		data['status'] = 'SUCCESS'
	else:
		data['status'] = 'ERROR'
	return JsonResponse(data)

# 用户退出登录
def logout(request):
	auth.logout(request)
	return redirect(request.GET.get('from', '/'))

# 进入注册页面
def register(request):
    redirect_to = request.GET.get('from', '/')
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            password = register_form.cleaned_data['password']
            nickname = register_form.cleaned_data['nickname']
            email = register_form.cleaned_data['email']
            # 注册成功创建新用户
            user = User.objects.create_user(username, email, password)
            user.save()
            # 保存用户的昵称
            profile, created = Profile.objects.get_or_create(user=user)
            profile.nickname = nickname
            profile.save()
            # 清除session
            del request.session['register_code']
            # 登录用户
            user = auth.authenticate(username=username, password=password)
            auth.login(request, user)
            return redirect(redirect_to)
    else:
        register_form = RegisterForm()

    context = {}
    context['register_form'] = register_form
    return render(request, 'user/register.html', context)

# 进入用户个人中心
def user_info(request):
	context = {}
	return render(request, 'user/base_info.html', context)

# 修改昵称模块
def change_nickname(request):
	redirect_to = request.GET.get('from', '/')
	if request.method == "POST":
		form = ChangeNicknameForm(request.POST, user=request.user)
		if form.is_valid():
			nickname_new = form.cleaned_data['nickname_new']
			profile, created = Profile.objects.get_or_create(user=request.user)
			profile.nickname = nickname_new
			profile.save()
			return redirect(redirect_to)
	else:
		form = ChangeNicknameForm()

	context = {}
	context['page_title'] = '修改昵称'
	context['form_title'] = '修改昵称'
	context['submit_text'] = '修改'
	context['form'] = form
	context['return_back_url'] = redirect_to
	return render(request, 'form.html', context)

# 绑定邮箱模块
def bind_email(request):
	redirect_to = request.GET.get('from', '/')
	if request.method == "POST":
		form = BindEmailForm(request.POST, request=request)
		if form.is_valid():
			email = form.cleaned_data['email']
			request.user.email = email
			request.user.save()
			# 清除session
			del request.session['bind_email_code']
			return redirect(redirect_to)
	else:
		form = BindEmailForm()

	context = {}
	context['page_title'] = '绑定邮箱'
	context['form_title'] = '绑定邮箱'
	context['submit_text'] = '绑定'
	context['form'] = form
	context['return_back_url'] = redirect_to
	return render(request, 'user/bind_email.html', context)

# 发送验证码模块
def send_verfication_code(request):
	email = request.GET.get('email', '')
	send_for = request.GET.get('send_for', '')
	print(email)
	data = {}
	if email != '':
		# 生成验证码
		code = ''.join(random.sample(string.ascii_letters + string.digits, 4))
		now = int(time.time())
		send_code_time = request.session.get('send_code_time', 0)
		if now - send_code_time < 30:
			data['status'] = 'ERROR'
		else:
			request.session[send_for] = code
			request.session['send_code_time'] = now
			# 发送邮件
			send_mail(
				'绑定邮箱',
			    '验证码： %s' % code,
			    '870850834@qq.com',
			    [email],
			    fail_silently=False,
			)
			data['status'] = 'SUCCESS'
	else:
		data['status'] = 'ERROR'
	return JsonResponse(data)

# 修改密码模块
def change_password(request):
    redirect_to = request.GET.get('from', '/')
    print(redirect_to)
    if request.method == "POST":
        form = ChangePasswordForm(request.POST, user=request.user)
        if form.is_valid():
            user = request.user
            new_password = form.cleaned_data['new_password']
            user.set_password(new_password)
            user.save()
            auth.logout(request)
            return redirect('user:login')
    else:
        form = ChangePasswordForm()

    context = {}
    context['page_title'] = '修改密码'
    context['form_title'] = '修改密码'
    context['submit_text'] = '修改'
    context['form'] = form
    context['return_back_url'] = redirect_to
    return render(request, 'form.html', context)


# 忘记密码模块
def forgot_password(request):
    redirect_to = request.GET.get('from', '/')
    if request.method == "POST":
        form = ForgotPasswordForm(request.POST, request=request)
        if form.is_valid():
            email = form.cleaned_data['email']
            new_password = form.cleaned_data['new_password']
            user = User.objects.get(email=email)
            user.set_password(new_password)
            user.save()
            # 清除session
            del request.session['forgot_password_code']
            return redirect(redirect_to)
    else:
        form = ForgotPasswordForm()

    context = {}
    context['page_title'] = '忘记密码'
    context['form_title'] = '忘记密码'
    context['submit_text'] = '修改'
    context['form'] = form
    context['return_back_url'] = redirect_to
    return render(request, 'user/forgot_password.html', context)

user/templates/user/base_info.html
{% extends 'user/user_info.html' %}

{% block base_status %}active{% endblock %}

{% block info_content %}
	<div class="base-info">
		<ul class="user-info-ul">
			<li>
				<span class="info-head">昵称</span>
				<span class="info-body">
					{{ user.get_nickname }}
					<a href="{% url 'user:change_nickname' %}?from={{ request.get_full_path }}">修改昵称</a>
				</span>
			</li>
			<li>
				<span class="info-head">邮箱</span>
				<span class="info-body">
					{% if user.email %}
						{{ user.email }}
					{% else %}
						未绑定<a href="{% url 'user:bind_email' %}?from={{ request.get_full_path }}">绑定邮箱</a>
					{% endif %}
				</span>
			</li>
			<li>
				<span class="info-head">
					密码
				</span>
				<span class="info-body">
					<a href="{% url 'user:change_password' %}?from={{ request.get_full_path }}">修改密码</a>
				</span>
			</li>
			<li>
				<span class="info-head">上一次登录时间</span>
				<span class="info-body">
					{{ user.last_login|date:"Y-m-d H:n:s" }}
				</span>
			</li>
			
		</ul>
	</div>
{% endblock %}

user/templates/user/bind_email.html
{% extends 'form.html' %}

{% block other_buttons %}
	<button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}

{% block script_extends %}
	<script type="text/javascript">
		$('#send_code').click(function(){
			$("#tip").text('')
			var email = $('#id_email').val();
			if(email==""){
				$("#tip").text('* 邮箱不能为空')
				return false;
			}

			// 发送验证码
			$.ajax({
				url: "{% url 'user:send_verfication_code' %}",
				type: "GET",
				data: {
					'email': email,
					'send_for': 'bind_email_code',
				},
				cache: false,
				success: function(data){
					if(data['status']=='ERROR'){
						alert(data['status']);
					}
				}
			});

			// 把按钮变灰
			$(this).addClass('disabled');
			$(this).attr('disabled', true);
			var time = 30;
			$(this).text(time + 's');
			var interval = setInterval(() => {
				if(time <= 0){
					clearInterval(interval);
					$(this).removeClass('disabled');
					$(this).attr('disabled', false);
					$(this).text('发送验证码');
					return false;
				}
				time --;
				$(this).text(time + 's');
			}, 1000);
		})
	</script>
{% endblock %}

user/templates/user/forgot_password.html
{% extends 'form.html' %}

{% block other_buttons %}
	<button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}

{% block script_extends %}
	<script type="text/javascript">
		$('#send_code').click(function(){
			$("#tip").text('')
			var email = $('#id_email').val();
			if(email==""){
				$("#tip").text('* 邮箱不能为空')
				return false;
			}

			// 发送验证码
			$.ajax({
				url: "{% url 'user:send_verfication_code' %}",
				type: "GET",
				data: {
					'email': email,
					'send_for': 'forgot_password_code',
				},
				cache: false,
				success: function(data){
					if(data['status']=='ERROR'){
						alert(data['status']);
					}
				}
			});

			// 把按钮变灰
			$(this).addClass('disabled');
			$(this).attr('disabled', true);
			var time = 30;
			$(this).text(time + 's');
			var interval = setInterval(() => {
				if(time <= 0){
					clearInterval(interval);
					$(this).removeClass('disabled');
					$(this).attr('disabled', false);
					$(this).text('发送验证码');
					return false;
				}
				time --;
				$(this).text(time + 's');
			}, 1000);
		})
	</script>
{% endblock %}

user/templates/user/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
	小黑阅读站|登录
{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">登录</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in login_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span id="tip" class="text-danger">
                                	{{ login_form.non_field_errors }}
                                </span>
                                <div class="clearfix"></div>     
                                <a style="margin-top: 8px; display: inline-block;" 
                                href="{% url 'user:forgot_password' %}?from={{ request.get_full_path }}" tabindex=-1>忘记密码？</a>                          
                                <input type="submit" value="登录" class="btn btn-primary pull-right">
                            </form>
                        </div>
                    </div>
                    {% if request.GET.from %}
                        <a style="text-align: center; display: block;" href="{% url 'user:register' %}?from={{ request.GET.from }}">前往注册 &gt;&gt;</a>
                    {% else %}
                        <a style="text-align: center; display: block;" href="{% url 'user:register' %}?from={{ request.get_full_path }}">前往注册 &gt;&gt;</a>
                    {% endif %}                    
                {% else %}
                    <span>已登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}              
            </div>
        </div>
	</div>
	
{% endblock %}

user/templates/user/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
	小黑阅读站|注册
{% endblock %}

{% block content %}
	<div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">注册</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in register_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    	{% if field.id_for_label == 'id_email' %}    	
	                                        <div class="input-group">
	                                          	{{ field }}
	                                          	<span class="input-group-btn">
	                                             	<button id="send_code" class="btn btn-primary">
	                                              		发送验证码
	                                          		</button>
	                                          	</span>
	                                        </div>
	                                    {% else %}
	                                        {{ field }}
	                                    {% endif %}

                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span id="tip" class="text-danger">{{ reg_form.non_field_errors }}</span>
                                <div class="clearfix"></div>                               
                                <input type="submit" value="注册" class="btn btn-primary pull-right">
                            </form>
                        </div>
                    </div>    
                    {% if request.GET.from %}
                        <a style="text-align: center; display: block;" href="{% url 'user:login' %}?from={{ request.GET.from }}">前往登录 &gt;&gt;</a>
                    {% else %}
                        <a style="text-align: center; display: block;" href="{% url 'user:login' %}?from={{ request.get_full_path }}">前往登录 &gt;&gt;</a>
                    {% endif %}
                    
                {% else %}
                    <span>已登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}              
            </div>
        </div>
    </div>    
	
{% endblock %}

{% block script_extends %}
	<script type="text/javascript">
		$('#send_code').click(function(){
			$("#tip").text('')
			var email = $('#id_email').val();
			if(email==""){
				$("#tip").text('* 邮箱不能为空')
				return false;
			}

			// 发送验证码
			$.ajax({
				url: "{% url 'user:send_verfication_code' %}",
				type: "GET",
				data: {
					'email': email,
					'send_for': 'register_code',
				},
				cache: false,
				success: function(data){
					if(data['status']=='ERROR'){
						alert(data['status']);
					}
				}
			});

			// 把按钮变灰
			$(this).addClass('disabled');
			$(this).attr('disabled', true);
			var time = 30;
			$(this).text(time + 's');
			var interval = setInterval(() => {
				if(time <= 0){
					clearInterval(interval);
					$(this).removeClass('disabled');
					$(this).attr('disabled', false);
					$(this).text('发送验证码');
					return false;
				}
				time --;
				$(this).text(time + 's');
			}, 1000);
		})
	</script>
{% endblock %}

user/templates/user/user_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}小黑阅读站|个人中心{% endblock %}

{% block header %}
	<link rel="stylesheet" type="text/css" href="{% static 'user/infoStyle.css' %}">
{% endblock header%}

{% block navbar %}
	<ul class="nav navbar-nav">
        <li>
            <a href="{% url 'index' %}">首页</a>
        </li>
        <li class="active">
            <a href="{% url 'user:user_info' %}">个人中心</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
	<div class="container">
		{% if user.is_authenticated %}
		<div class="row">
			<div class="col-xs-10 col-xs-offset-1">
				<h2>{{ user.username }}</h2>
				
				<ul class="nav nav-tabs nav-justified">
					<li role="presentation" class="{% block base_status %}{% endblock %}">
						<a href="{% url 'user:user_info' %}">基本信息</a>
					</li>
					<li role="presentation" class="{% block collect_status %}{% endblock %}">
						<a href="{% url 'collect:my_collects' %}">我的收藏</a>
					</li>
					<li role="presentation" class="{% block message_status %}{% endblock %}">
						<a href="{% url 'my_notifications:my_notifications' %}">我的消息</a>
					</li>
				</ul>
				{% block info_content %}
				{% endblock %}
				
			</div>
		</div>
		{% else %}
			<span>您还没有登录，请先登录...</span>
			<script type="text/javascript">
				window.location.href = '{% url "user:login" %}';
			</script>
		{% endif %}
	</div>
{% endblock %}