my_notifications/urls.py
from django.urls import path
from . import views

app_name = "my_notifications"

urlpatterns = [
	path('', views.my_notifications, name="my_notifications"),
    path('my_notification<int:my_notification_pk>/', views.my_notification, name="my_notification"),
    path('delete_my_read_notifications/', views.delete_my_read_notifications, name="delete_my_read_notifications"),
]

novels/urls.py
from django.urls import path
from . import views

app_name = 'novels'

urlpatterns = [
    path('type<int:type_pk>/', views.type, name="type"),
    path('novel_detail<int:novel_pk>', views.novel_detail, name="novel_detail"),
]

search/urls.py
from django.urls import path
from . import views

app_name = "search"
# start with blog
urlpatterns = [
	path('', views.search, name="search"),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('login_for_modal/', views.login_for_modal, name="login_for_modal"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('user_info/', views.user_info, name="user_info"),
    path('change_nickname/', views.change_nickname, name="change_nickname"),
    path('bind_email/', views.bind_email, name="bind_email"),
    path('send_verfication_code/', views.send_verfication_code, name="send_verfication_code"),
    path('change_password/', views.change_password, name="change_password"),
    path('forgot_password', views.forgot_password, name="forgot_password"),
]

my_notifications/models.py
from django.db import models

# Create your models here.

my_notifications/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from notifications.models import Notification

# 查看站内消息
def my_notifications(request):
	return render(request, 'my_notifications/my_notifications.html')

# 查看具体某一条消息，并把它标记为已读
def my_notification(request, my_notification_pk):
	my_notification = get_object_or_404(Notification, pk=my_notification_pk)
	my_notification.unread = False
	my_notification.save()
	return redirect(my_notification.data['url'])

# 删除全部已读消息
def delete_my_read_notifications(request):
	notifications = request.user.notifications.read()
	notifications.delete()
	return redirect(reverse('my_notifications:my_notifications'))

templates/base.html
{% load staticfiles %}
{% load noveltype_tags %}
{% load notifications_tags %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}小黑阅读站{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/baseStyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">  
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'notifications/notify.js' %}"></script>
    {% block header %}{% endblock header %}
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index' %}">小黑阅读站</a>

                <button class="navbar-toggle collapsed"  data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar-collapse" class="collapse navbar-collapse">
                {% block navbar %}
                {% endblock %}
                <ul class="nav navbar-nav navbar-right">
                    <form action="{% url 'search:search' %}" class="navbar-form navbar-left search" method="GET">
                        <div class="input-group">
                            <input type="text" class="form-control" name="search_content" 
                            placeholder="请输入书名或作者">
                            <span class="input-group-btn">
                                <input class="btn btn-default" type="submit" value="搜索" >
                            </span>
                        </div>
                    </form>
                    {% if not user.is_authenticated %}      
                        <li>
                            <a href="{% url 'user:login' %}?from={{ request.get_full_path }}">
                                登录
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'user:register' %}?from={{ request.get_full_path }}">   注册
                            </a> 
                        </li>
                    {% else %}
                        {% notifications_unread as unread_count %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
                            role="button">
                                {% if user.has_nickname %}
                                    {{ user.get_nickname }}
                                    <span class="badge unread-count live_notify_badge">
                                        {% if unread_count > 0 %}{{ unread_count }}{% endif %}
                                    </span>
                                {% else %}
                                    {{ user.username }} 
                                {% endif %}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'user:user_info' %}">个人中心</a></li>
                                <li>
                                    <a href="{% url 'my_notifications:my_notifications' %}">
                                        我的消息
                                        <span class="badge unread-count live_notify_badge">
                                            {% if unread_count > 0 %}{{ unread_count }}{% endif %}
                                        </span>
                                    </a>
                                </li>
                                {% if user.is_staff or user.is_superuser %}
                                    <li><a href="{% url 'admin:index' %}">后台管理</a></li>
                                {% endif %}
                                <li>
                                    <a href="{% url 'user:logout' %}?from={{ request.get_full_path }}">退出</a>
                                </li>
                            </ul>
                        </li>
                    {% endif %} 
                </ul>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
    <!-- footer -->
    <div class="footer">
        <div class="website-info">
            <p>小黑阅读站 小黑你好么么哒 版权所有</p>
            <p>意见反馈或联系我（870850834@qq.com）</p>
        </div>
    </div>
    <script type="text/javascript">
        //底部栏置底
        //窗体改变大小事件
        $(window).resize(function(){
            //正文高度
            var body_height = $(document.body).outerHeight(true);
            //底部元素高度
            var bottom_height = $("#footer").outerHeight(true);
            //浏览器页面高度
            var window_height = $(window).height();
            //判断并调整底部元素的样式
            if($(".footer").hasClass('page-bottom')){
                //若包含有page-bottom类，就应用了position设置
                //当position为absolute时，body高度不包含这个元素
                //所以页面高度需要判断body和footer之和若小于浏览器窗口
                //则移除样式，让footer自然跟随在正文后面
                if(body_height + bottom_height >= window_height){
                    $(".footer").removeClass('page-bottom');
                }
            }else{
                //若没有page-bottom类，body高度包含footer
                //判断body高度小于浏览器时，则悬浮于底部
                if(body_height < window_height){
                    $(".footer").addClass('page-bottom');
                }
            }
        });
        //页面加载时，模拟触发一下resize事件
        $(window).trigger('resize');
        
        //自定义实时获取未读消息
        function my_special_notification_callback(data){
            unread_count = data['unread_count'];
            if (unread_count == 0) {
                unread_count = '';
            }
            $('.live_notify_badge').text(unread_count);
        }
    </script>
    {% register_notify_callbacks callbacks='my_special_notification_callback' %}
    {% block script_extends %}{% endblock %}  
</body>
</html>

templates/form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
	小黑阅读站|{{ page_title }}
{% endblock title %}

{% block header %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/formStyle.css' %}">
{% endblock header %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-xs-4 col-xs-offset-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">{{ form_title }}</h3>
					</div>
					<div class="panel-body">
						<form action="" method="POST">
							{% csrf_token %}
							{% for field in form %}
								{% if not field.is_hidden %}
									<label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    	{% if field.id_for_label == 'id_verification_code' %}
	                                        <div class="input-group">
	                                          	{{ field }}
	                                          	<span class="input-group-btn">
	                                             	<button id="send_code" class="btn btn-default">
	                                              		发送验证码
	                                          		</button>
	                                          	</span>
	                                        </div>
	                                    {% else %}
	                                        {{ field }}
	                                    {% endif %}
								{% endif %}
								
								<p class="text-danger">{{ field.errors.as_text }}</p>
							{% endfor %}
							<span id="tip" class="text-danger">{{ form.non_field_errors }}</span>
							<div class="clearfix"></div>
							<div class="pull-left">
								{% block other_buttons %}{% endblock %}
							</div>
							<div class="pull-right">
								<input type="submit" value="{{ submit_text }}" 
								       class="btn btn-primary">
								<a class="btn btn-default" href="{{ return_back_url }}">返回</a>
								</button>
							</div>	
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/index.html
{% extends "index_base.html" %}
{% load noveltype_tags %}
{% load notifications_tags %}
{% load staticfiles %}
{% block title %}小黑阅读站|首页{% endblock title %}
{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/indexStyle.css' %}">
{% endblock header %}
{% block content1 %}
    <div class="recommend-container">
        <ul class="recommend-ul">
            {% for novel_info in novels_info %}
                <li>
                    <a target="_blank" href="{% url 'novels:novel_detail' novel_info.novel.pk %}" 
                    title="{{ novel_info.novel.novel_name }}" class="novel-image-border">
                        <img class="novel-image" src="{{ novel_info.image }}" alt="配图" 
                        onerror="this.src='{% static "image/nocover.jpg" %}'">
                    </a>
                    <img src="
                               {% if novel_info.state == '连载' %}
                               {% static 'image/only2.png' %}
                               {% else %}
                               {% static 'image/only.png' %}
                               {% endif %}"
                         class="state-image">
                    <div class="novel-info">
                        <a target="_blank" href="{% url 'novels:novel_detail' novel_info.novel.pk %}" title="{{ novel_info.novel.novel_name }}" class="novel-name">
                            {{ novel_info.novel.novel_name }}
                        </a>
                        <a target="_blank" href="{% url 'novels:type' novel_info.novel.novel_type.pk %}" class="novel-type">
                            类别：<span>{{ novel_info.novel.novel_type.type_name }}</span>
                        </a>
                        <a class="novel-author" title="{{ novel_info.author }}">
                            作者：<span>{{ novel_info.author }}</span>
                        </a>
                    </div>
                    
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="novel-type-container">
        <div class="touch-nav">
            <span class="nav-title">精彩推荐：</span>
            <ul class="nav-title-ul">
                <li class="hover" id="title_1" onmouseover="changeTab('title',1,5)">玄幻魔法</li>
                <li id="title_2" onmouseover="changeTab('title',2,5)">武侠修真</li>
                <li id="title_3" onmouseover="changeTab('title',3,5)">都市言情</li>
                <li id="title_4" onmouseover="changeTab('title',4,5)">职场校园</li>
                <li id="title_5" onmouseover="changeTab('title',5,5)">穿越重生</li>
            </ul>
        </div>
        {% for novels_info in novels_types_info %}
            <div class="con-div" id="title_con_{{ forloop.counter }}" 
            style="display: {% if forloop.counter == 1 %}
                                block
                            {% else %}
                                none
                            {% endif %}">
                <ul class="con-ul">
                    {% for novel_info in novels_info %}
                        <li>
                            <div class="con-novel">
                                <a target="_blank" href="{% url 'novels:novel_detail' novel_info.novel.pk %}" 
                                title="{{ novel_info.novel.novel_name }}">
                                    <img src="{{ novel_info.image }}" class="con-novel-image" 
                                    onerror="this.src='{% static "image/nocover.jpg" %}'">
                                </a>
                                <img src="
                                       {% if novel_info.state == '连载' %}
                                       {% static 'image/only2.png' %}
                                       {% else %}
                                       {% static 'image/only.png' %}
                                       {% endif %}"
                                    class="state-image1">
                                <div class="con-novel-info">
                                    <a target="_blank" 
                                    href="{% url 'novels:novel_detail' novel_info.novel.pk %}" 
                                    title="{{ novel_info.novel.novel_name }}" 
                                    class="con-novel-name">
                                        {{ novel_info.novel.novel_name }}
                                    </a>
                                    <span class="con-novel-author">
                                        作者：{{ novel_info.author }}
                                    </span>
                                    <span class="con-novel-des">{{ novel_info.description }}</span>
                                    <a target="_blank" href="{% url 'novels:novel_detail' novel_info.novel.pk %}" class="btn btn-primary readTo"
                                    title="{{ novel_info.novel.novel_name }}">马上阅读</a>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>  
        {% endfor %}
    </div>
    <div class="listContainer">
        <div class="row">
            <div class="col-xs-7">
                <div class="updateList">
                    <div class="update-head">
                        <span class="update-title">刚刚更新的：</span>
                    </div>
                    <div class="update-body">
                        {% for novel_info in novels_last_update %}
                            <div class="last-update-novel-info">
                                <ul class="last-update-ul">
                                    <li>
                                        <a class="update-novel-name" target="_blank" 
                                        href="{% url 'novels:novel_detail' novel_info.novel.pk %}">
                                            {{ novel_info.novel.novel_name }}
                                        </a>
                                    </li>
                                    <li>
                                        <span class="last-update-time">
                                            更新时间：{{ novel_info.last_update_time }}
                                        </span>
                                    </li>
                                    <li>
                                        <span class="last-update-author">
                                            {{ novel_info.author }}
                                        </span>
                                    </li>
                                </ul>
                            </div>
                        {% empty %}
                            暂无更新
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-xs-5">
                <div class="likeList">
                    <div class="like-head">
                        <span class="like-title">点赞排行榜：</span>
                    </div>
                    <div class="like-body">
                        {% for novel_like in novels_like_list %}
                            <div class="novel-like-record-info">
                                <ul class="novel-like-ul">
                                    <li>
                                        <a class="novel-like-name" target="_blank" 
                                        href="{% url 'novels:novel_detail' novel_like.content_object.pk %}">
                                            {{ novel_like.content_object.novel_name }}
                                        </a>
                                    </li>
                                    <li>
                                        <span class="novel-like-num">
                                            点赞数：{{ novel_like.liked_num }}
                                        </span>
                                    </li> 
                                </ul>
                            </div>
                        {% empty %}
                            暂无点赞记录
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script_extends %}
    <script>
        function changeTab(name, i, a) {
            for (v = 1; v <= a; v++) {
                var til = document.getElementById(name + "_" + v)
                var con = document.getElementById(name + "_con_" + v)
                til.className = v == i ? 'hover' : '';
                con.style.display = v == i ? 'block' : 'none'
            }
        }
    </script>
{% endblock %}

templates/index_base.html
{% extends "base.html" %}
{% load noveltype_tags %}
{% load notifications_tags %}
{% load staticfiles %}
{% block title %}小黑阅读站|首页{% endblock title %}
{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/baseStyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/indexStyle.css' %}">
{% endblock header %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <div class="logo-container">
                    <div class="col-xs-5 logo">
                        <img src="{% static 'image/logo.png' %}" alt="logo">
                    </div>
                </div>
                <div class="main-nav">
                    <ul class="nav-ul">
                        <li><a href="{% url 'index' %}">首页</a></li>
                        {% get_novel_type as novel_types %}
                        {% for novel_type in novel_types %}
                            <li>
                                <a href="{% url 'novels:type' novel_type.pk %}">
                                    {{ novel_type.type_name }}
                                </a>
                            </li>
                        {% endfor %}
                        <li class="active"><a href="{% url 'user:user_info' %}">个人中心</a></li>
                        <li><a href="http://www.baidu.com">热门排行</a></li>
                    </ul>
                </div>
                {% block content1 %}
                {% endblock %}
            </div>
        </div>   
    </div>
{% endblock %}

templates/my_notifications.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}小黑阅读站|我的消息{% endblock title %}
{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/indexStyle.css' %}">
{% endblock header %}
{% block content %}
{% endblock content %}